### ISSUE TITLE
Permalink support from URL

### ISSUE THREAD

**Issue by rahul286** [pushpakpop/Chirp#2]
No matter whose tweets I am viewing

URL in address bar remains - 
http://www.umawoodenpallet.com/rtcamp/chirp/home.php

For my tweet it should be:

http://www.umawoodenpallet.com/rtcamp/chirp/tweets/me

For user ABC, it should be

http://www.umawoodenpallet.com/rtcamp/chirp/tweets/ABC

And so on.

That way, I will be able to bookmark a user's tweet.

**Comment by pushpakpop** [comment]
I have implemented this using Hash URLs.

Now a user can bookmark any user's link.

Thanks you.
